### ISSUE TITLE
Package version

### ISSUE THREAD

**Issue by 1429904852** [peldszus/joty-rstparser-docker#1]
Hi, Can you provide a version of the package, such as:
python == 3.5
numpy == 1.8.0
......
I had a problem installing according to the Dockerfile

**Comment by peldszus** [comment]
Hi @1429904852!

First of all, sorry for answering just now. I didn't expect activity here and I must have missed the notification.

Thanks for reporting this issue. Building the docker image was indeed not possible anymore.

I pinned the python version of the used libraries to the versions that were up to date when I created this repository. With this, the docker image can be build again.

Also I made explicit in the dockerfile, that this image is using the python2.7 available in the base image.
